### ISSUE TITLE
Camp fires have the wrong color

### ISSUE THREAD

**Issue by F3hliks** [gri573/rethinking-voxels#85]
When placing a campfire, the color of the light they emit is wrong:
![2023-02-23_14 09 21](https://user-images.githubusercontent.com/55054659/220915590-f789eced-037f-469a-9152-860bd931a30d.png)
The warm light one is from 17a the new one is in 17b
![2023-02-23_14 09 29](https://user-images.githubusercontent.com/55054659/220915630-0554684f-5099-4458-a623-6590678fe9b2.png)

**Comment by gri573** [comment]
![image](https://user-images.githubusercontent.com/66473137/221231856-9ee6dde4-53fd-46bd-ae79-8e92dc3b2fda.png)
reproduced, and fixed in the latest commit

**Comment by zndrmn** [comment]
I'm still seeing some green here and there on commit: [`70c4652`](https://github.com/gri573/rethinking-voxels/commit/70c4652d724fc4ffdba74fb981fd861f5e6ecf05)

![2023-02-26_21 17 54_4](https://user-images.githubusercontent.com/77690119/221465333-70decf90-9200-4be9-93ab-dbcae345ba8c.png)

**Comment by Potato22** [comment]
![image](https://user-images.githubusercontent.com/39096741/221575339-87395882-c32d-41ca-bef2-d2cd477b2531.png)
Verified and repeatable, any fire or lava source has a green tint.

**Comment by Potato22** [comment]
That's greatly good to hear, looking forward 👍

**Comment by gri573** [comment]
the release with the fix has been out for a while, I've just forgotten about closing this issue
